name: build ⚙️

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tox-env: py37-extra
            python-version: "3.7"
          - tox-env: py38-extra
            python-version: "3.8"
          - tox-env: py39-extra
            python-version: "3.9"
          - tox-env: py310-extra
            python-version: "3.10"
          - tox-env: py311-extra
            python-version: "3.11"
    steps:
    - uses: actions/checkout@v3
    - name: Install packages 📦
      run: |
        sudo apt-get update
        sudo apt-get -y install libnetcdf-dev libhdf5-dev
    - uses: actions/setup-python@v4
      name: Setup Python ${{ matrix.python-version }}
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run flake8 ⚙️
      run: |
        pip install flake8
        flake8 pywps
      if: matrix.python-version == 3.7
    - name: Install tox 📦
      run: pip install "tox>=4.0"
    - name: Run tests with tox ⚙️
      run: tox -e ${{ matrix.tox-env }}
    - name: Run coveralls ⚙️
      if: matrix.python-version == 3.7
      uses: AndreMiras/coveralls-python-action@develop

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        name: Setup Python 3.7
        with:
          python-version: 3.7
      - name: Build docs 🏗️
        run: |
          pip install -e .[dev]
          cd docs && make html
